# Generated by Django 5.0.6 on 2024-07-06 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="total_payment",
        ),
        migrations.AddField(
            model_name="organization",
            name="user_profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("organization", "Organization"),
                    ("accountant", "Accountant"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="OrganizationSubscription",
        ),
    ]
