# Generated by Django 5.0.6 on 2024-07-06 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_organization_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.organization",
            ),
        ),
    ]
