# Generated by Django 5.0.6 on 2024-07-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_organizationsubscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="student",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="organization",
        ),
        migrations.AddField(
            model_name="payment",
            name="organizationsubscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.organizationsubscription",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="organizationsubscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.organizationsubscription",
            ),
        ),
    ]
