# Generated by Django 5.0.6 on 2024-07-06 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_payment_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="student",
        ),
    ]
