# Generated by Django 5.0.6 on 2024-07-06 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_remove_payment_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.student",
            ),
        ),
    ]
