# Generated by Django 5.0.6 on 2024-07-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_payment_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paymentdate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="paymentdate",
            field=models.DateField(null=True),
        ),
    ]
